### ISSUE TITLE
Following another User

### ISSUE THREAD

**Issue by bhball22** [Intro-to-SE-Spring-21/Group-8#11]
As a user I want to be able to follow another user’s account

### Sub Stories:
- As a user I want to be able to navigate to the desired account I want to follow
- As a user I want to be able to select the account I want to follow and view their profile page
- As a user I want to be able to select the follow button on the account profile page
- As a user I want to be able to see the followed account's tweets and interactions on my feed

### Task Issues:
- [x] Create Accounts
- [x] #33  Create simple profile page
- [x] #30  Create Account directory on homepage
- [x] Create a Follow model inside 'Account/models.py' that contains two foreign keys
  - [x] One foreign key for the person who is doing the following
  - [x] One foreign key for the person who is getting the follow (that is all we should need I think.)

- [x] Make the follow button on profile page dynamic POST button.
  - [x] The action should just the url to the same page. (Check the registerAccount files for a good example
  - [x] Update the profile.view with an if else. One for POST, and one for GET.
  - [x]  When a POST is called...check to see if the follow button was called and then grab the user who is currently logged in, and then grab the user whose profile page is being followed, and then add that to the 'Follow' model

### Things that will also be needed in a different issue probably:
*  Replace the follow button with an unfollow button that does the reverse action
* Live update the follow and following counts.

### Acceptance Criteria:
- The user can successfully navigate to the list of accounts
- The user can successfully select the follow button under another users account
- The user can follow another user.
- The user can view who they are following under their profile page

**Comment by lmurdock12** [comment]
Pulled in and merged with develop
