### ISSUE TITLE
Removing a Like

### ISSUE THREAD

**Issue by bhball22** [Intro-to-SE-Spring-21/Group-8#18]
As a user I would like to remove a like from a tweet that I previously liked

## Sub Stories:

- As a user I want to navigate to the desired tweet
- As a user I want to be able to select the ‘Like tweet’ button
- As a user I want to see my like removed from the post
- As a user I want to see the number of likes updated under the tweet

## Task Issues:

- [x] Implement the removeLike() function inside of the GenericPage class.
  - [x] This removes a like from the database given a user and a tweet ID
 - [x] Update the POST in both MainPage and ProfilePage classes so that the removeLike() function is called when the button is selected.

Acceptance Criteria:

- A user can only "unlike" if they have already "liked" the tweet
- The user can successfully unlike a post and the database is updated
- Once a user unlikes the post the button will change back to "like"
