### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by bhball22** [Intro-to-SE-Spring-21/Group-8#22]
A simple login page needs to be created that is integrated into the Django authentication system.

### Task Issues:

- [x] Make sure the admin page is already setup <localhost>/admin
  * Setup a superuser (admin) if not already created
- [x] Make sure accounts is enabled inside the Django application
- [x]  Create a login/logout link (href) in the top right corner of the website.
  * This links into the 'account/login' URL and view
- [x] Create a basic login.html file inside the appropriate directory that the login link will redirect to.
- [x]  Ensure the form submits to the appropriate location using a "POST" 
- [x] Make the login/logout link dynamically update depending whether the user is logged in or not.

### Acceptance Criteria:

A user can select login from the homepage.
- [x] The user is redirected to the login page
- [x] Upon a successful login they are brought back to the homepage
- [x] Upon an incorrect login an error is shown asking the user to renter information

A user can select logout from the homepage
- [x] The user is logged out and the session is ended.

### Notes

Test using the super user

### References

* https://docs.djangoproject.com/en/3.1/topics/auth/default/
* https://docs.djangoproject.com/en/3.1/topics/auth/default/#built-in-auth-forms
* https://www.youtube.com/watch?v=dBctY3-Z5hY

**Comment by lmurdock12** [comment]
This issue is pretty much ready. Will add a pull request once develop branch is up to date

**Comment by lmurdock12** [comment]
Merged into develop
