### ISSUE TITLE
Create Simple homepage 

### ISSUE THREAD

**Issue by lmurdock12** [Intro-to-SE-Spring-21/Group-8#30]
A simple homepage needs to be built for the website.

### Task Issues:

- [x] Design a simplistic layout as a template in the "base.html" file
- [x] Extend the base.html file in the index.html file under the main app (Live_scroll or whatever the name is)
- [x] Inside the index view...grab the current account names on the system using a model query <sup>1</sup> , and pass it along to 'index.html' as a context variable. 
  * Do not list every single account...instead just grab like 5 or 10 accounts. When we have a lot of accounts on the site we would not want to list 100 accounts in one small container
- [x] Use the context variable inside the 'index.html' to loop through and list the users inside the appropriate <div> that contains the acounts

Acceptance Criteria:
- The name of the website ('Twitter') should be displayed in the top banner.
- An example of where the tweets would be located is shown
- The 'Accounts' section lists 5-10 accounts that is dynamically pulled from the database

<sup>1</sup>https://docs.djangoproject.com/en/3.1/ref/models/querysets/
