### ISSUE TITLE
Create simple profile page

### ISSUE THREAD

**Issue by lmurdock12** [Intro-to-SE-Spring-21/Group-8#33]
Create a simple profile page for a given user.

### Tasks 

- [x] Create a blank profile page view that uses a dynamic url (twitter.com/profile/lucian)
- [x] Pass along the account object to the context for the html to use
- [x] Create a base.html file that shows what the general look of the account page would look like.
  * Can copy a lot of the current homepage html...but instead of the tweets section make a profile section
 - [x] List the profile name, 
 - [x] have  a place for # of followers and # of followings,  
 - [x] Create a follow button next to the name 
 - [x] Have the tabs of "tweets" and "likes" under that

### Acceptance Criteria:

- The URL should be custom: ex: twitter.com/<username>/profile
-  Display the name and username
-  Have a placeholder with fake info follower numbers and following numbers
- Have placeholder for follow button 
- Placeholder for user tweets.
- Placeholder for user likes.

**Comment by lmurdock12** [comment]
Finished and pulled into develop
