### ISSUE TITLE
Update the 'Login' and 'Join' on the profile page

### ISSUE THREAD

**Issue by lmurdock12** [Intro-to-SE-Spring-21/Group-8#44]
As a user if I would like to be able to login from a given profile page by select 'Login' and being redirected to the login page.

(Implement basically the same thing as the homepage login/logout page)
## Tasks

- [x] Check the implementation of the login links inside the main_page's 'index.html'
- [x] Add django template code to the profile.html so that if the user is not logged in then the 'login' link and 'join' link show
- [x] Add logic to the template so that if the user is logged in only the 'logout' link should show 

Acceptance Criteria 

* If the user is not currently logged in the "Login" link and the "join" link should show
* If the user is currently logged in just the "Logout" link should show
* All links should be clickable and redirect to the appropriate form
