### ISSUE TITLE
Update the Accounts on the sidebar of the profile page

### ISSUE THREAD

**Issue by lmurdock12** [Intro-to-SE-Spring-21/Group-8#45]
As a user if I would like to be able to see a couple accounts under the "Who to follow" block on the righthand sidebar.

## Tasks

- [x] Check the implementation of the 'who to follow' section on the homepage in the views.py file and the index.html file
- [x] Copy over that implementation into the Account 'profile.html' and 'views.py'
  - [x] Add the python logic to generate three random users (comes from the index function)
  - [x] Pass that created dictionary into the context  (see index for example)
  - [x] Update profile.html so the information from the users is dynamically shown.

Note:

* Any code you add to profile() inside views.py should go after the if conditional that checks for 'request.method=="POST"
* The follow buttons do not have to be working in this issue. 

## Acceptance Criteria 

* The 'who to follow' section should match the 'who to follow' section as seen on the current homepage.
*  Three random accounts should be shown each time on the profile page

**Comment by lmurdock12** [comment]
Merged into develop.
