### ISSUE TITLE
Followers and Following Tab

### ISSUE THREAD

**Issue by lmurdock12** [Intro-to-SE-Spring-21/Group-8#87]
As a user I would like to be able to select "Followers" or "Following" on a profile page and see the list of user accounts in place of where the tweets are shown on the profile page.

## Tasks

- [x] Create clickable "POST" buttons for the 'Following' and 'Followers' tab.
- [x] Update the 'post' function inside 'ProfilePage' to grab the appropriate data needed.
- [x] Update the Django template.html to render the appropriate data.

## Acceptance Criteria

If the user selects the 'following' button then all the people that the profile follows will be shown.
If the user selects the  'follower' button then all the people who follow that profile will be shown.

## Notes:

One approach to solve this would be to create the context dictionary inside the ProfilePage.post() function and pass it along to the ProfilePage.get() (get renders the page). Inside ProfilePage.get() you can check to see if a context was passed in, and depending on what was in that context you will know whether to render the tweets or the followers, etc...

For example:

Say the user clicks the following tab, ProfilePage.post() gets called. Inside .post() grab all the followers needed and add that to an empty context dictionary(). You could also add a 'render' item that could be set to either 'tweets', 'followers', or 'following'. You could use this so the Django template knows what to render. 

 At the end of .post(), .get() gets called and this context dictionary gets passed into .get(). .get() is the function that actually renders the page. .get() can check to see if a context dictionary was passed in, and if so it can just add the other context items need to that same dictionary. If no context dictionary was passed in it can just create one like the function already does, and set the 'render' item to Tweets (the default thing we show on a profile page).

**Comment by bhball22** [comment]
Following Tab works perfectly, the Followers Tab buttons needs work. Although the output of the Users is subject to change due to things like photos and Bio

**Comment by bhball22** [comment]
Finalized Pushing the data up now.
