### ISSUE TITLE
Add photo's to profile picture

### ISSUE THREAD

**Issue by lmurdock12** [Intro-to-SE-Spring-21/Group-8#89]
As a user I would like to be able to view my profile picture across the site. Right now this could just be a basic default profile picture.

## Tasks

- [x] Research how to implement photos and photo storage on website
- [x] Add a default profile photo image
- [x] Make this image be properly shown throughout all places on the website
  - [x] Homepage
  - [x] Profile Page
  - [x] On the tweet block
  - [x] on the "other users" block

## Acceptance Criteria

The user can see the default profile page across the website.
No more default empty image blocks can be seen.
